import GlobalPopup from '@/common/components/popup/GlobalPopup'
import './globals.css'
import type { Metadata } from 'next'
import RecoilProviders from '@/common/utils/RecoilProviders'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body>
          <RecoilProviders>
            {children}
            <GlobalPopup />
          </RecoilProviders>
        </body>
      </html>
  )
}
